#!/usr/bin/env bash

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

git clone https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/zdharma/fast-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/fast-syntax-highlighting
git clone https://github.com/djui/alias-tips.git ~/.oh-my-zsh/custom/plugins/alias-tips

if [ $(which brew) ]; then
    echo 'brew already installed'
else 
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew tap homebrew/cask-fonts
brew cask install font-hack-nerd-font
brew tap AdoptOpenJDK/openjdk
brew cask install adoptopenjdk8
#brew cask install adoptopenjdk11
brew cask install gpg-suite
for formulae in `cat ./misc/brew.list`; do
    brew install $formulae
done

curl -L https://git.io/n-install | bash

for p in `cat ./misc/npm.list`; do
    npm i -g $p
done


