#!/usr/bin/env bash

if [ $(which brew) ]; then
    echo 'brew already installed'
else 
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew tap AdoptOpenJDK/openjdk
brew cask install adoptopenjdk8

for formulae in `cat ./misc/brew.list`; do
    brew install $formulae
done

curl -L https://git.io/n-install | bash

for p in `cat ./misc/npm.list`; do
    npm i -g $p
done


